# Generated by Django 6.0.3 on 2026-04-12 07:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_moment_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 4, 12, 7, 7, 28, 480470, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
